version: '3.7'

services:
  backend:
    build: ./backend/simple-api-student
    networks:
      - app-network
    depends_on:
      - postgres

  postgres:
    build: ./postgres
    networks:
      - app-network

  http:
    build: ./http
    ports:
      - "80:80" 
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
