
- name: Run App Container
  docker_container:
    name: "{{ contAPP }}"
    image: "theoahga/my-backend:latest"
    networks:
      - name: "{{ networkName }}"
    env:
      DBURL: "{{ dbURL }}"
      DBUSER: "{{ dbUSER }}"
      DBPWD: "{{ dbPWD }}"
