name: CI devops 2023
on:

  push:
    branches: 
    - main
    - develop
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: "adopt"

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

     #finally vamoooos build your app with the latest command
      - name: Build and test with Maven
        run: |
              cd backend/simple-api-student
              mvn clean test
        # --file ./backend/simple-api-student/pom.xml

# define job to build and publish docker image
build-and-push-docker-image:
 needs: test-backend
 runs-on: ubuntu-22.04

 steps:
   - name: Checkout code
     uses: actions/checkout@v2.5.0

   - name: Build image and push backend
     uses: docker/build-push-action@v3
     with:
       context: ./backend/simple-api/
       tags:  ${{secrets.DOCKERHUB_USERNAME}}/backend:latest

   #- name: Build image and push database
       # DO the same for database

   #- name: Build image and push httpd
     # DO the same for httpd
